filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: ""
  password: ""

setup.kibana:
  host: "grafana:5601"
