---
- name: Restart webserver
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart suricata
  ansible.builtin.service:
    name: suricata
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
