name: CI Full

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r docker/app/requirements.txt
      - name: Run flake8
        run: flake8 || true
      - name: Run pytest
        run: pytest docker/app/tests -q

  build-and-scan:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t poudlard-app:latest -f docker/app/Dockerfile ./docker/app
      - name: Trivy scan (placeholder)
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: poudlard-app:latest
          format: 'json'
          output: 'trivy-report.json'

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.11
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  push:
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and Push image to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/poudlard-app:latest
          docker tag poudlard-app:latest $IMAGE
          docker push $IMAGE
