name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install flake8
        run: |
          pip install flake8
          flake8 --version || true
      - name: Run flake8
        run: flake8 || true

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install
        run: pip install -r docker/app/requirements.txt
      - name: Run tests
        run: |
          echo "No tests yet" && exit 0

  build:
    runs-on: ubuntu-latest
    needs: [lint, tests]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker build -t poudlard-app:latest -f docker/app/Dockerfile ./docker/app

  sonar:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: SonarQube scan (placeholder)
        run: echo "Run SonarQube scanner here"
